import { Driver, Vehicle, Alert, ComplianceStatus, CompanyInfo, IncidentReport, HistoricalViolation } from './types';

export const DEFAULT_COMPANY_INFO: CompanyInfo = {
  legalName: 'FastGate Logistics Inc.',
  dbaName: 'FastGate Freight Lines',
  usdotNumber: '3892019',
  mcNumber: 'MC-1092841',
  feinTaxId: '36-9812019',
  address: '1000 S Financial Place, Suite 2400, Chicago, IL 60605',
  phone: '(800) 555-3533',
  email: 'safety@fastgatelogistics.com',
  safetyManagerName: 'Alice Johnson',
  iftaAccountState: 'IL',
  iftaAccountNumber: 'IL-IFTA-98102',
  stateTaxWithholdingId: 'IL-W2-381920',
  bankName: 'Chase Bank NA (Operating)',
  payrollRoutingNumber: '*****0210',
  payrollAccountNumber: '*****9012'
};

const getStatus = (expiryDate: string): ComplianceStatus => {
  const expiry = new Date(expiryDate);
  const today = new Date();
  const diffTime = expiry.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays < 0) return 'NON-COMPLIANT';
  if (diffDays <= 30) return 'Warning';
  return 'Compliant';
};

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'D2',
    name: 'James Wilson',
    cdlExpiry: '2026-04-05',
    medCertExpiry: '2026-04-10',
    truckId: 'TRK-202',
    overallStatus: getStatus('2026-04-05'),
    criticalViolations: 3,
    isHighRisk: true,
    taxClassification: '1099-NEC',
    profileInfo: {
      phone: '(214) 555-8821',
      email: 'j.wilson@wilsonlogistics.net',
      address: '402 Elm Street, Dallas, TX 75201',
      emergencyContactName: 'Sarah Wilson',
      emergencyContactPhone: '(214) 555-9012',
      ssnEin: '401-XX-2819',
      cdlNumber: 'TX-CDL-2049182',
      cdlState: 'TX',
      endorsements: ['Tanker'],
      hireDate: '2022-09-01',
      bankName: 'Bank of America',
      routingNumber: '*****1110',
      accountNumber: '*****3921',
      payRatePerMile: 0.85,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D3',
    name: 'Sarah Miller',
    cdlExpiry: '2026-03-15',
    medCertExpiry: '2026-03-20',
    truckId: 'TRK-303',
    overallStatus: getStatus('2026-03-15'),
    criticalViolations: 1,
    isHighRisk: false,
    taxClassification: 'W2',
    profileInfo: {
      phone: '(404) 555-3910',
      email: 'sarah.miller@fastgatelogistics.com',
      address: '782 Peachtree St NE, Atlanta, GA 30308',
      emergencyContactName: 'David Miller',
      emergencyContactPhone: '(404) 555-8811',
      ssnEin: '290-XX-8711',
      cdlNumber: 'GA-CDL-9042811',
      cdlState: 'GA',
      endorsements: ['HazMat', 'Reefer'],
      hireDate: '2024-01-10',
      bankName: 'Wells Fargo',
      routingNumber: '*****0560',
      accountNumber: '*****1049',
      payRatePerMile: 0.68,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D4',
    name: 'Robert Brown',
    cdlExpiry: '2026-06-01',
    medCertExpiry: '2026-07-10',
    truckId: 'TRK-404',
    overallStatus: getStatus('2026-06-01'),
    criticalViolations: 4,
    isHighRisk: true,
    taxClassification: '1099-NEC',
    profileInfo: {
      phone: '(313) 555-4921',
      email: 'rbrown.freight@gmail.com',
      address: '1201 Woodward Ave, Detroit, MI 48226',
      emergencyContactName: 'Martha Brown',
      emergencyContactPhone: '(313) 555-7090',
      ssnEin: '38-9201948',
      cdlNumber: 'MI-CDL-1102948',
      cdlState: 'MI',
      endorsements: ['Double/Triple'],
      hireDate: '2021-11-15',
      bankName: 'Huntington National',
      routingNumber: '*****0019',
      accountNumber: '*****4820',
      payRatePerMile: 0.82,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D5',
    name: 'Linda Garcia',
    cdlExpiry: '2026-04-25',
    medCertExpiry: '2026-05-30',
    truckId: 'TRK-505',
    overallStatus: getStatus('2026-04-25'),
    criticalViolations: 0,
    isHighRisk: false,
    taxClassification: 'W2',
    profileInfo: {
      phone: '(305) 555-9012',
      email: 'linda.garcia@fastgatelogistics.com',
      address: '350 Ocean Drive, Miami, FL 33139',
      emergencyContactName: 'Carlos Garcia',
      emergencyContactPhone: '(305) 555-4491',
      ssnEin: '261-XX-9014',
      cdlNumber: 'FL-CDL-4920192',
      cdlState: 'FL',
      endorsements: ['HazMat', 'Tanker'],
      hireDate: '2023-08-20',
      bankName: 'PNC Bank',
      routingNumber: '*****0021',
      accountNumber: '*****9012',
      payRatePerMile: 0.70,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D6',
    name: 'Michael Chen',
    cdlExpiry: '2026-03-01',
    medCertExpiry: '2026-03-15',
    truckId: 'TRK-606',
    overallStatus: getStatus('2026-03-01'),
    criticalViolations: 2,
    isHighRisk: true,
    taxClassification: '1099-NEC',
    profileInfo: {
      phone: '(213) 555-2019',
      email: 'mchen.hauling@outlook.com',
      address: '888 Wilshire Blvd, Los Angeles, CA 90017',
      emergencyContactName: 'Grace Chen',
      emergencyContactPhone: '(213) 555-8833',
      ssnEin: '95-8492019',
      cdlNumber: 'CA-CDL-8019284',
      cdlState: 'CA',
      endorsements: ['Tanker', 'Reefer'],
      hireDate: '2022-05-10',
      bankName: 'U.S. Bank',
      routingNumber: '*****1220',
      accountNumber: '*****7821',
      payRatePerMile: 0.88,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D7',
    name: 'Emily Davis',
    cdlExpiry: '2026-08-15',
    medCertExpiry: '2026-09-20',
    truckId: 'TRK-707',
    overallStatus: getStatus('2026-08-15'),
    criticalViolations: 0,
    isHighRisk: false,
    taxClassification: 'W2',
    profileInfo: {
      phone: '(206) 555-7819',
      email: 'emily.davis@fastgatelogistics.com',
      address: '1501 4th Ave, Seattle, WA 98101',
      emergencyContactName: 'Mark Davis',
      emergencyContactPhone: '(206) 555-1029',
      ssnEin: '531-XX-4912',
      cdlNumber: 'WA-CDL-3019284',
      cdlState: 'WA',
      endorsements: ['Double/Triple'],
      hireDate: '2024-02-01',
      bankName: 'Chase Bank NA',
      routingNumber: '*****0210',
      accountNumber: '*****4491',
      payRatePerMile: 0.69,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D8',
    name: 'David Martinez',
    cdlExpiry: '2026-04-15',
    medCertExpiry: '2026-04-20',
    truckId: 'TRK-808',
    overallStatus: getStatus('2026-04-15'),
    criticalViolations: 1,
    isHighRisk: false,
    taxClassification: '1099-NEC',
    profileInfo: {
      phone: '(602) 555-1920',
      email: 'dmartinez.trucking@gmail.com',
      address: '201 Washington St, Phoenix, AZ 85004',
      emergencyContactName: 'Maria Martinez',
      emergencyContactPhone: '(602) 555-3388',
      ssnEin: '86-3029184',
      cdlNumber: 'AZ-CDL-7019283',
      cdlState: 'AZ',
      endorsements: ['HazMat'],
      hireDate: '2023-10-12',
      bankName: 'Wells Fargo',
      routingNumber: '*****0560',
      accountNumber: '*****2091',
      payRatePerMile: 0.80,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D9',
    name: 'Jessica Taylor',
    cdlExpiry: '2026-10-10',
    medCertExpiry: '2026-11-05',
    truckId: 'TRK-909',
    overallStatus: getStatus('2026-10-10'),
    criticalViolations: 0,
    isHighRisk: false,
    taxClassification: 'W2',
    profileInfo: {
      phone: '(615) 555-4019',
      email: 'jessica.taylor@fastgatelogistics.com',
      address: '401 Commerce St, Nashville, TN 37219',
      emergencyContactName: 'Thomas Taylor',
      emergencyContactPhone: '(615) 555-7822',
      ssnEin: '410-XX-7781',
      cdlNumber: 'TN-CDL-9018273',
      cdlState: 'TN',
      endorsements: ['Tanker', 'Reefer'],
      hireDate: '2023-06-18',
      bankName: 'First Horizon',
      routingNumber: '*****0192',
      accountNumber: '*****5519',
      payRatePerMile: 0.71,
      operatingStatus: 'Active'
    }
  },
  {
    id: 'D10',
    name: 'Kevin Lee',
    cdlExpiry: '2026-03-25',
    medCertExpiry: '2026-04-01',
    truckId: 'TRK-1010',
    overallStatus: getStatus('2026-03-25'),
    criticalViolations: 5,
    isHighRisk: true,
    taxClassification: '1099-NEC',
    profileInfo: {
      phone: '(303) 555-9102',
      email: 'klee.express@yahoo.com',
      address: '1700 Lincoln St, Denver, CO 80203',
      emergencyContactName: 'Susan Lee',
      emergencyContactPhone: '(303) 555-6611',
      ssnEin: '84-1029384',
      cdlNumber: 'CO-CDL-5019284',
      cdlState: 'CO',
      endorsements: ['Double/Triple'],
      hireDate: '2022-01-15',
      bankName: 'FirstBank',
      routingNumber: '*****1029',
      accountNumber: '*****3019',
      payRatePerMile: 0.84,
      operatingStatus: 'Active'
    }
  }
];

export const MOCK_VEHICLES: Vehicle[] = [
  { id: 'V1', unitNumber: 'TRK-101', vin: '1FVAC99283X...', inspectionExpiry: '2026-08-20', overallStatus: getStatus('2026-08-20'), maintenanceStatus: 'Up to Date', mileage: 65200, lastInspectionMileage: 60100, inspectionIntervalMiles: 10000, averageMonthlyMiles: 4000 },
  { id: 'V2', unitNumber: 'TRK-202', vin: '1FVAC11204Y...', inspectionExpiry: '2026-04-05', overallStatus: getStatus('2026-04-05'), maintenanceStatus: 'Scheduled', mileage: 124800, lastInspectionMileage: 115000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 4800 },
  { id: 'V3', unitNumber: 'TRK-303', vin: '1FVAC44592Z...', inspectionExpiry: '2026-03-15', overallStatus: getStatus('2026-03-15'), maintenanceStatus: 'Overdue', mileage: 245000, lastInspectionMileage: 232000, inspectionIntervalMiles: 12000, averageMonthlyMiles: 5000 },
  { id: 'V4', unitNumber: 'TRK-404', vin: '1FVAC88321A...', inspectionExpiry: '2026-06-01', overallStatus: getStatus('2026-06-01'), maintenanceStatus: 'Up to Date', mileage: 82000, lastInspectionMileage: 74000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 3200 },
  { id: 'V5', unitNumber: 'TRK-505', vin: '1FVAC55678B...', inspectionExpiry: '2026-04-25', overallStatus: getStatus('2026-04-25'), maintenanceStatus: 'Scheduled', mileage: 147200, lastInspectionMileage: 138000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 4200 },
  { id: 'V6', unitNumber: 'TRK-606', vin: '1FVAC66789C...', inspectionExpiry: '2026-03-01', overallStatus: getStatus('2026-03-01'), maintenanceStatus: 'Overdue', mileage: 198000, lastInspectionMileage: 185000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 5100 },
  { id: 'V7', unitNumber: 'TRK-707', vin: '1FVAC77890D...', inspectionExpiry: '2026-08-15', overallStatus: getStatus('2026-08-15'), maintenanceStatus: 'Up to Date', mileage: 44000, lastInspectionMileage: 40000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 3000 },
  { id: 'V8', unitNumber: 'TRK-808', vin: '1FVAC88901E...', inspectionExpiry: '2026-04-15', overallStatus: getStatus('2026-04-15'), maintenanceStatus: 'Scheduled', mileage: 111100, lastInspectionMileage: 102000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 4500 },
  { id: 'V9', unitNumber: 'TRK-909', vin: '1FVAC99012F...', inspectionExpiry: '2026-10-10', overallStatus: getStatus('2026-10-10'), maintenanceStatus: 'Up to Date', mileage: 98100, lastInspectionMileage: 95000, inspectionIntervalMiles: 10000, averageMonthlyMiles: 2900 },
  { id: 'V10', unitNumber: 'TRK-1010', vin: '1FVAC00123G...', inspectionExpiry: '2026-03-25', overallStatus: getStatus('2026-03-25'), maintenanceStatus: 'Overdue', mileage: 293400, lastInspectionMileage: 280000, inspectionIntervalMiles: 12000, averageMonthlyMiles: 5500 },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'A1',
    timestamp: '2026-04-01 09:00',
    type: 'Compliance',
    message: 'Medical Card for James Wilson expires in 9 days.',
    severity: 'medium',
  },
  {
    id: 'A2',
    timestamp: '2026-04-01 10:30',
    type: 'Safety',
    message: 'Robert Brown flagged for high-risk safety review (>2 critical violations).',
    severity: 'high',
  },
  {
    id: 'A3',
    timestamp: '2026-04-01 11:15',
    type: 'Maintenance',
    message: 'Vehicle TRK-303 inspection has EXPIRED.',
    severity: 'high',
  },
];

export const MOCK_INCIDENTS: IncidentReport[] = [
  {
    id: 'INC-4102',
    driverId: 'D6',
    driverName: 'Michael Chen',
    driverPhone: '(213) 555-2019',
    truckId: 'TRK-606',
    type: 'Mechanical Breakdown',
    severity: 'Major',
    status: 'Resolved / Cleared',
    location: 'I-15 Northbound, Mile Marker 98 near Barstow, CA',
    reportedAt: '2026-04-12 09:30',
    resolvedAt: '2026-04-12 14:15',
    description: 'Alternator failure caused low voltage shutdown. Technician replaced alternator on site.',
    isVehicleDrivable: false,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Mobile Roadside Mechanic'],
    serviceVendor: 'Barstow Heavy Diesel Repair',
    dispatchNotes: 'Technician completed replacement and tested charge at 14.2V. Cleared to resume route.'
  },
  {
    id: 'INC-4250',
    driverId: 'D8',
    driverName: 'David Martinez',
    driverPhone: '(602) 555-1920',
    truckId: 'TRK-808',
    type: 'DOT Roadside Inspection',
    severity: 'Critical',
    status: 'Resolved / Cleared',
    location: 'I-10 Weigh Station, Ehrenberg, AZ',
    reportedAt: '2026-04-28 16:45',
    resolvedAt: '2026-04-28 19:30',
    description: 'Level 2 roadside inspection citation for inoperative tail lamps and tire pressure alert.',
    isVehicleDrivable: true,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Safety Inspection Clearance'],
    dispatchNotes: 'Lamps replaced and reinspected by officer. Out-of-service condition lifted.'
  },
  {
    id: 'INC-4389',
    driverId: 'D3',
    driverName: 'Robert Brown',
    driverPhone: '(901) 555-0182',
    truckId: 'TRK-303',
    type: 'Cargo Shift / HazMat Issue',
    severity: 'Major',
    status: 'Resolved / Cleared',
    location: 'I-40 Eastbound, Mile Marker 42 near Little Rock, AR',
    reportedAt: '2026-05-15 11:20',
    resolvedAt: '2026-05-16 08:30',
    description: 'Severe pallet banding break during sudden brake maneuver. Pulled into rest area for restrapping.',
    isVehicleDrivable: true,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Cargo Restrap Crew'],
    dispatchNotes: 'Secondary securing chains and edge protectors verified by local dock team.'
  },
  {
    id: 'INC-4819',
    driverId: 'D2',
    driverName: 'James Wilson',
    driverPhone: '(312) 555-0143',
    truckId: 'TRK-202',
    loadId: 'LD-3942',
    type: 'Tire Blowout',
    severity: 'Major',
    status: 'In Progress - Assistance Dispatched',
    location: 'I-80 Eastbound, Mile Marker 174 near Davenport, IA',
    reportedAt: '2026-05-24 13:20',
    description: 'Right drive axle outer tire blew out with loud tread separation. Pulled safely onto wide paved right shoulder with hazard flashers on and safety triangles positioned 100ft back. Rim intact, no cargo or brake line damage.',
    isVehicleDrivable: false,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Tire Replacement Unit', 'Mobile Roadside Mechanic'],
    serviceVendor: "Love's Truck Tire Care (Davenport)",
    etaMinutes: 30,
    dispatchNotes: "Dispatched Love's Roadside unit #4. Tech en route with 295/75R22.5 Michelin drive tire. ETA ~30 mins. Driver confirmed safe on shoulder."
  },
  {
    id: 'INC-5120',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    driverPhone: '(303) 555-9102',
    truckId: 'TRK-1010',
    type: 'Mechanical Breakdown',
    severity: 'Major',
    status: 'Resolved / Cleared',
    location: 'I-70 Westbound, Eisenhower Tunnel Approach, CO',
    reportedAt: '2026-06-18 10:15',
    resolvedAt: '2026-06-18 15:45',
    description: 'Coolant hose clamp ruptured on steep grade. Heavy steam. Pulled into chain-up station.',
    isVehicleDrivable: false,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Heavy-Duty Tow / Winch', 'Mobile Roadside Mechanic'],
    serviceVendor: 'High Rockies Mobile Diesel',
    dispatchNotes: 'Hose replaced and coolant bled. Engine checked for head gasket integrity, test passed.'
  },
  {
    id: 'INC-5481',
    driverId: 'D5',
    driverName: 'Sarah Jenkins',
    driverPhone: '(404) 555-8910',
    truckId: 'TRK-505',
    type: 'Other Roadside Issue',
    severity: 'Minor',
    status: 'Resolved / Cleared',
    location: 'I-75 Southbound, Exit 212 near McDonough, GA',
    reportedAt: '2026-07-22 14:10',
    resolvedAt: '2026-07-22 17:00',
    description: 'Electronic logging device (ELD) Bluetooth gateway lost connection with vehicle ECM.',
    isVehicleDrivable: true,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['ELD Technical Support'],
    dispatchNotes: 'Firmware reset remotely by Omnitracs dispatch desk. Switched to manual paper log backup temporarily.'
  },
  {
    id: 'INC-5890',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    driverPhone: '(303) 555-9102',
    truckId: 'TRK-1010',
    type: 'DOT Roadside Inspection',
    severity: 'Critical',
    status: 'Resolved / Cleared',
    location: 'I-80 Port of Entry, Evanston, WY',
    reportedAt: '2026-07-30 08:45',
    resolvedAt: '2026-07-30 13:20',
    description: 'Level 1 full DOT inspection. Citation issued for improper lane change and missing fire extinguisher seal.',
    isVehicleDrivable: true,
    injuriesReported: false,
    policeContacted: true,
    assistanceNeeded: ['Safety Inspection Clearance'],
    dispatchNotes: 'Replaced cab extinguisher and documented fine payment. Released by state patrol.'
  },
  {
    id: 'INC-6023',
    driverId: 'D8',
    driverName: 'David Martinez',
    driverPhone: '(602) 555-1920',
    truckId: 'TRK-808',
    type: 'Mechanical Breakdown',
    severity: 'Minor',
    status: 'Resolved / Cleared',
    location: 'I-40 Eastbound, Mile Marker 195 near Flagstaff, AZ',
    reportedAt: '2026-08-19 15:30',
    resolvedAt: '2026-08-19 18:00',
    description: 'Air conditioning compressor seized, causing serpentine belt squeal and odor.',
    isVehicleDrivable: true,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Mobile Roadside Mechanic'],
    dispatchNotes: 'Short bypass belt installed so truck could reach Phoenix depot without stranding.'
  },
  {
    id: 'INC-6210',
    driverId: 'D3',
    driverName: 'Robert Brown',
    driverPhone: '(901) 555-0182',
    truckId: 'TRK-303',
    type: 'Tire Blowout',
    severity: 'Major',
    status: 'Open - Dispatch Action Required',
    location: 'I-55 Southbound, Mile Marker 88 near Cape Girardeau, MO',
    reportedAt: '2026-08-29 11:40',
    description: 'Trailer rear tandem outer tire bead failure. Low pressure alarm sounded prior to tread de-lamination.',
    isVehicleDrivable: false,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Tire Replacement Unit'],
    dispatchNotes: 'Awaiting local vendor dispatch approval from Fleet Safety Manager.'
  },
  {
    id: 'INC-6340',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    driverPhone: '(303) 555-9102',
    truckId: 'TRK-1010',
    type: 'Mechanical Breakdown',
    severity: 'Critical',
    status: 'Open - Dispatch Action Required',
    location: 'I-76 Eastbound, Mile Marker 64 near Brush, CO',
    reportedAt: '2026-09-03 08:15',
    description: 'Sudden loss of oil pressure indicator and high temperature warning. Pulled to shoulder immediately, oil puddle observed underneath oil pan.',
    isVehicleDrivable: false,
    injuriesReported: false,
    policeContacted: false,
    assistanceNeeded: ['Heavy-Duty Tow / Winch', 'Mobile Roadside Mechanic'],
    dispatchNotes: 'Truck immobilized. Wrecker requested to haul unit to Freightliner Sterling dealership.'
  }
];

export const HISTORICAL_VIOLATIONS: HistoricalViolation[] = [
  // April 2026
  {
    id: 'HV-101',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    date: '2026-04-10',
    type: '14-Hour Driving Window Exceeded (HOS)',
    category: 'Hours of Service',
    severity: 'Critical',
    points: 10,
    fmcsaCode: '395.3(a)(2)',
    location: 'Nebraska Scale Facility I-80'
  },
  {
    id: 'HV-102',
    driverId: 'D3',
    driverName: 'Robert Brown',
    date: '2026-04-18',
    type: 'Brake Systems: Clamp / Roto Chamber Out of Adjustment',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 8,
    fmcsaCode: '396.3(a)(1)',
    location: 'Arkansas DOT Inspection Point'
  },
  {
    id: 'HV-103',
    driverId: 'D8',
    driverName: 'David Martinez',
    date: '2026-04-26',
    type: 'Operating with Inoperable Tail Lamps',
    category: 'Vehicle Maintenance',
    severity: 'Warning',
    points: 3,
    fmcsaCode: '393.9',
    location: 'Ehrenberg, AZ Weigh Station'
  },
  // May 2026
  {
    id: 'HV-104',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    date: '2026-05-08',
    type: 'False Report of Records of Duty Status',
    category: 'Hours of Service',
    severity: 'Critical',
    points: 10,
    fmcsaCode: '395.8(e)',
    location: 'Colorado State Patrol Inspection'
  },
  {
    id: 'HV-105',
    driverId: 'D6',
    driverName: 'Michael Chen',
    date: '2026-05-19',
    type: 'Speeding 15+ MPH Over Construction Zone Limit',
    category: 'Unsafe Driving',
    severity: 'Critical',
    points: 10,
    fmcsaCode: '392.2S2',
    location: 'Barstow, CA Highway Patrol'
  },
  {
    id: 'HV-106',
    driverId: 'D2',
    driverName: 'James Wilson',
    date: '2026-05-24',
    type: 'Tire Ply Separation / Audible Tread Failure',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 6,
    fmcsaCode: '393.75(a)',
    location: 'Iowa DOT Inspection I-80'
  },
  // June 2026
  {
    id: 'HV-107',
    driverId: 'D3',
    driverName: 'Robert Brown',
    date: '2026-06-12',
    type: 'Defective Parking Brake / Emergency Stop Mechanism',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 8,
    fmcsaCode: '393.41',
    location: 'Tennessee Weigh Station I-40'
  },
  {
    id: 'HV-108',
    driverId: 'D8',
    driverName: 'David Martinez',
    date: '2026-06-25',
    type: 'Operating Motor Vehicle with Flat Tire',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 6,
    fmcsaCode: '393.75(c)',
    location: 'New Mexico Port of Entry'
  },
  // July 2026
  {
    id: 'HV-109',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    date: '2026-07-14',
    type: 'Improper Lane Change / Unsafe Weaving in Traffic',
    category: 'Unsafe Driving',
    severity: 'Critical',
    points: 7,
    fmcsaCode: '392.2LC',
    location: 'Wyoming Highway Patrol'
  },
  {
    id: 'HV-110',
    driverId: 'D6',
    driverName: 'Michael Chen',
    date: '2026-07-28',
    type: 'Axle Weight Exceeding Permitted Tolerances (2,400 lbs)',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 5,
    fmcsaCode: '392.9(a)',
    location: 'Banning, CA Scale Facility'
  },
  {
    id: 'HV-111',
    driverId: 'D7',
    driverName: 'Emily Davis',
    date: '2026-07-19',
    type: 'Failing to Carry Physical Medical Examiner Certificate in Cab',
    category: 'Driver Fitness',
    severity: 'Warning',
    points: 2,
    fmcsaCode: '391.41(a)',
    location: 'Washington State Patrol I-5'
  },
  // August 2026
  {
    id: 'HV-112',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    date: '2026-08-04',
    type: 'Driving While Disqualified / Suspended in State of Colorado',
    category: 'Driver Fitness',
    severity: 'Critical',
    points: 10,
    fmcsaCode: '391.15(a)',
    location: 'Denver Metro DOT Enforcement'
  },
  {
    id: 'HV-113',
    driverId: 'D3',
    driverName: 'Robert Brown',
    date: '2026-08-22',
    type: 'Driving Beyond 11-Hour Daily Maximum Window',
    category: 'Hours of Service',
    severity: 'Critical',
    points: 9,
    fmcsaCode: '395.3(a)(1)',
    location: 'Missouri Highway Patrol I-55'
  },
  {
    id: 'HV-114',
    driverId: 'D9',
    driverName: 'Jessica Taylor',
    date: '2026-08-15',
    type: 'Minor Windshield Crack on Passenger Sweep Zone',
    category: 'Vehicle Maintenance',
    severity: 'Warning',
    points: 1,
    fmcsaCode: '393.60(c)',
    location: 'Kentucky Scale Facility'
  },
  // September 2026
  {
    id: 'HV-115',
    driverId: 'D10',
    driverName: 'Kevin Lee',
    date: '2026-09-02',
    type: 'Failure to Complete Annual Periodic Vehicle Inspection',
    category: 'Vehicle Maintenance',
    severity: 'Critical',
    points: 7,
    fmcsaCode: '396.17(c)',
    location: 'Colorado DOT Roadside Checkpoint'
  }
];
